[mypy]
mypy_path = python

[mypy-MySQLdb.*]
ignore_missing_imports = True
[mypy-imdb.*]
ignore_missing_imports = True
[mypy-MediaInfoDLL3.*]
ignore_missing_imports = True
[mypy-download.*]
ignore_missing_imports = True

[mypy-mysql.*]
ignore_missing_imports = True
