.PHONY: search
search:
	apt-cache search paranoia
	apt-cache search ripp | grep KDE
	apt-cache search ripper
.PHONY: search_gnome
search_gnome:
	apt-cache search ripp | grep GNOME
.PHONY: search_kde
search_kde:
	apt-cache search ripp | grep KDE
.PHONY: search_qt
search_qt:
	apt-cache search ripp | grep qt

.PHONY: ripp
ripp:
	eject -t
	sleep 10
	pacpl  --rip all --to mp3 --outdir . --nscheme="%ar|%ab|%tr|%ti"
	eject
	spd-say "Ripping done. please enter another CD"
